const STORE_JWT = 'STORE_JWT';
const GET_COURSE_INFO = 'GET_COURSE_INFO';
const STORE_STUDENT_ID = 'STORE_STUDENT_ID';
const LOGOUT = 'LOGOUT';
const TAB_CHANGE = 'TAB_CHANGE';
export { STORE_JWT, GET_COURSE_INFO, STORE_STUDENT_ID, LOGOUT, TAB_CHANGE };
